@startuml

package com.kf.coffeecard{
    class AbstractService
    class GameProxyService{
        -Game mGame
        +Game GetGameInfo()
    }
    class GameFactory{
        -Game mGame
        -static GameFactory mInstance
        +void createGame();
    }
    class Game{
        +enum GameType{
            BRIDGE,
            BLACK_JACK,
            SEVENS,
            LIAR;}
    }
    class BridgeGame{
        -GameType mGameType
        -GameRule mRule
        -Player[] mPlayers
        +void startGame()
        -void Deal()
    }
    class CardSet
    class Player
    class GameRule

    GameProxyService --|>AbstractService

    BridgeGame --|> Game
    Game <--* GameFactory

    BridgeGame <--o CardSet
    GameProxyService --> GameFactory

    Game <--o Player
    Game <--o GameRule
}

package com.kf.coffeecard.activity{
    class MainActivity
    class SettingActivity
    class BridgeGameActivity

    MainActivity --> SettingActivity
    SettingActivity <--> GameProxyService:start/bind service
    SettingActivity --> BridgeGameActivity
    BridgeGameActivity<--> GameProxyService:bind service
}

@enduml